name: Build and Deploy Smotrilka

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set IMAGE name
        run: echo "IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/smotrilka" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/smotrilka:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/smotrilka:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT || '22' }}
          script: |
            IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/smotrilka
            TAG=latest
            TARGET_DIR="/home/${{ secrets.SERVER_SSH_USER }}/smotrilka"

            mkdir -p "$TARGET_DIR"

            docker pull $IMAGE:$TAG

            docker stop smotrilka-app || true
            docker rm smotrilka-app || true

            docker run -d \
              --name smotrilka-app \
              --restart=always \
              -p 9090:9090 \
              -v "$TARGET_DIR/demo.db":/app/demo.db \
              $IMAGE:$TAG

            docker ps --filter "name=smotrilka-app" --format "table  {{.Names}}\t{{.Image}}\t{{.Ports}}"
